package emacs.mem_limits;
import org.bridj.BridJ;
import org.bridj.CRuntime;
import org.bridj.Pointer;
import org.bridj.ann.Library;
import org.bridj.ann.Runtime;
/**
 * Wrapper for library <b>mem_limits</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mem_limits") 
@Runtime(CRuntime.class) 
public class Mem_limitsLibrary {
	static {
		BridJ.register();
	}
	/**
	 * Original signature : <code>char* start_of_data()</code><br>
	 * <i>native declaration : mem_limits.h:280</i>
	 */
	public static native Pointer<Byte > start_of_data();
}
