package emacs.macros;
import org.bridj.BridJ;
import org.bridj.CRuntime;
import org.bridj.ann.Library;
import org.bridj.ann.Runtime;
/**
 * Wrapper for library <b>macros</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("macros") 
@Runtime(CRuntime.class) 
public class MacrosLibrary {
	static {
		BridJ.register();
	}
	/**
	 * Original signature : <code>void end_kbd_macro()</code><br>
	 * <i>native declaration : macros.h:3</i>
	 */
	public static native void end_kbd_macro();
	/**
	 * Original signature : <code>void finalize_kbd_macro_chars()</code><br>
	 * <i>native declaration : macros.h:5</i>
	 */
	public static native void finalize_kbd_macro_chars();
	/**
	 * Original signature : <code>void store_kbd_macro_char(Lisp_Object)</code><br>
	 * <i>native declaration : macros.h:7</i>
	 */
	public static native void store_kbd_macro_char(MacrosLibrary.Lisp_Object Lisp_Object1);
	/// Undefined type
	/// Undefined type
	public static interface Lisp_Object {
		
	};
	/// Undefined type
	/// Undefined type
	public static interface EMACS_INT {
		
	};
}
