package emacs.w32term;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : w32term.h:713</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("w32term") 
public class deferred_msg extends StructObject {
	public deferred_msg() {
		super();
	}
	/// C type : deferred_msg*
	@Field(0) 
	public Pointer<deferred_msg > next() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : deferred_msg*
	@Field(0) 
	public deferred_msg next(Pointer<deferred_msg > next) {
		this.io.setPointerField(this, 0, next);
		return this;
	}
	/// C type : W32Msg
	@Field(1) 
	public W32Msg w32msg() {
		return this.io.getNativeObjectField(this, 1);
	}
	/// C type : W32Msg
	@Field(1) 
	public deferred_msg w32msg(W32Msg w32msg) {
		this.io.setNativeObjectField(this, 1, w32msg);
		return this;
	}
	@Field(3) 
	public int completed() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public deferred_msg completed(int completed) {
		this.io.setIntField(this, 3, completed);
		return this;
	}
}
