package emacs.w32term;
import emacs.w32term.W32termLibrary.Lisp_Vector;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : w32term.h:686</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("w32term") 
public class scroll_bar extends StructObject {
	public scroll_bar() {
		super();
	}
	/// C type : Lisp_Vector*
	@Field(1) 
	public Pointer<Lisp_Vector > next_from_Lisp_Vector_struct() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : Lisp_Vector*
	@Field(1) 
	public scroll_bar next_from_Lisp_Vector_struct(Pointer<Lisp_Vector > next_from_Lisp_Vector_struct) {
		this.io.setPointerField(this, 1, next_from_Lisp_Vector_struct);
		return this;
	}
}
