#!/bin/sh

# TAGS-LISP,include just refuses to work

./make-emacs tags

cat emacs/src/TAGS* > TAGS

# Build a small tags file for the part we're interested in
cd emacs/src
../lib-src/etags -o TAGS-TEMACS --regex='/[     ]*DEFVAR_[A-Z_  (]+"\([^"]+\)"/' $(echo *.o | sed s/\\.o/.c/g)

# ;; To navigate between C and Emacs Lisp
# (require 'etags-select)
# (require 'etags-table)

# (global-set-key "\M-." 'etags-select-find-tag)
# (setq etags-table-search-up-depth 10)
