#!/bin/bash

EMACS_TAG=emacs-24.2

test -z `ls emacs` && git submodule update --init emacs
cd emacs
git checkout $EMACS_TAG

test -e ./configure || ./autogen.sh

# Investigate new --without-all option in 24.3
./configure -with-x=no --without-xpm --without-jpeg --without-tiff --without-gif --without-png \
    --without-toolkit-scroll-bars --without-xim --without-sound --without-makeinfo --without-selinux \
    --without-dbus --without-gsettings --without-gconf --without-gnutls
