#!/bin/bash

EMACS_VERSION=24.2

test -e emacs || curl -L http://ftp.gnu.org/pub/gnu/emacs/emacs-$EMACS_VERSION.tar.bz2 | tar xj

mv emacs-$EMACS_VERSION emacs 2> /dev/null

cd emacs

# LLVM is faster than gcc, at least without tweaking options, but broken atm.
# if [[ -e $(which llvm-gcc) ]] ; then
#     export CC=llvm-gcc
# fi

./configure -with-x=no --without-xpm --without-jpeg --without-tiff --without-gif --without-png \
    --without-toolkit-scroll-bars --without-xim --without-sound --without-makeinfo --without-selinux \
    --without-dbus --without-gsettings --without-gconf --without-gnutls
