#!/bin/sh -e

test -e emacs/src/Makefile || ./configure-emacs
test -e emacs/lisp/loaddefs.el || make -C emacs

rm -rf target/*

lein run -q --batch
lein uberjar
lein difftest

cat > target/deuce << EOF
#!/bin/sh

exec java -jar "\$0" "\$@"
EOF

cat `find target/deuce-*standalone.jar` >> target/deuce
chmod +x target/deuce
