#!/bin/sh -e

test -e emacs/src/Makefile || ./configure-emacs
test -e emacs/lisp/loaddefs.el || make -j -C emacs

rm -rf target/*

lein run -q --batch
lein uberjar
lein difftest

cat > target/deuce << EOF
#!/bin/sh

exec java -client -noverify -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -jar "\$0" -q "\$@"
exit
EOF

cat `find target/deuce-*standalone.jar` >> target/deuce
chmod +x target/deuce
