package emacs.w32inevt;
import org.bridj.BridJ;
import org.bridj.CRuntime;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.ann.CLong;
import org.bridj.ann.Library;
import org.bridj.ann.Runtime;
/**
 * Wrapper for library <b>w32inevt</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("w32inevt") 
@Runtime(CRuntime.class) 
public class W32inevtLibrary {
	static {
		BridJ.register();
	}
	/**
	 * Original signature : <code>int w32_console_read_socket(terminal*, int, input_event*)</code><br>
	 * <i>native declaration : w32inevt.h:1</i>
	 */
	public static native int w32_console_read_socket(Pointer<W32inevtLibrary.terminal > term, int numchars, Pointer<W32inevtLibrary.input_event > hold_quit);
	/**
	 * Original signature : <code>void w32_console_mouse_position(FRAME_PTR*, int, Lisp_Object*, scroll_bar_part*, Lisp_Object*, Lisp_Object*, unsigned long*)</code><br>
	 * <i>native declaration : w32inevt.h:3</i>
	 */
	public static native void w32_console_mouse_position(Pointer<W32inevtLibrary.FRAME_PTR > f, int insist, Pointer<W32inevtLibrary.Lisp_Object > bar_window, Pointer<IntValuedEnum<W32inevtLibrary.scroll_bar_part > > part, Pointer<W32inevtLibrary.Lisp_Object > x, Pointer<W32inevtLibrary.Lisp_Object > y, Pointer<CLong > time);
	/// Undefined type
	/// Undefined type
	public static interface FRAME_PTR {
		
	};
	/// Undefined type
	/// Undefined type
	public static interface terminal {
		
	};
	/// Undefined type
	/// Undefined type
	public static interface input_event {
		
	};
	/// Undefined type
	/// Undefined type
	public static interface Lisp_Object {
		
	};
}
