package emacs.ndir;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * data from readdir()<br>
 * <i>native declaration : ndir.h:7</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("ndir") 
public class direct extends StructObject {
	public direct() {
		super();
	}
	/// inode number of entry
	@CLong 
	@Field(0) 
	public long d_ino() {
		return this.io.getCLongField(this, 0);
	}
	/// inode number of entry
	@CLong 
	@Field(0) 
	public direct d_ino(long d_ino) {
		this.io.setCLongField(this, 0, d_ino);
		return this;
	}
	/// length of this record
	@Field(1) 
	public short d_reclen() {
		return this.io.getShortField(this, 1);
	}
	/// length of this record
	@Field(1) 
	public direct d_reclen(short d_reclen) {
		this.io.setShortField(this, 1, d_reclen);
		return this;
	}
	/// length of string in d_name
	@Field(2) 
	public short d_namlen() {
		return this.io.getShortField(this, 2);
	}
	/// length of string in d_name
	@Field(2) 
	public direct d_namlen(short d_namlen) {
		this.io.setShortField(this, 2, d_namlen);
		return this;
	}
	/**
	 * name of file<br>
	 * C type : char[15 + 1]
	 */
	@Array({15 + 1}) 
	@Field(3) 
	public Pointer<Byte > d_name() {
		return this.io.getPointerField(this, 3);
	}
}
