package emacs.nsgui;
import org.bridj.BridJ;
import org.bridj.CRuntime;
import org.bridj.ann.Library;
import org.bridj.ann.Runtime;
/**
 * Wrapper for library <b>nsgui</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("nsgui") 
@Runtime(CRuntime.class) 
public class NsguiLibrary {
	static {
		BridJ.register();
	}
	/// <i>native declaration : nsgui.h</i>
	public static final int GCBackground = (int)2;
	/// <i>native declaration : nsgui.h</i>
	public static final int PMaxSize = (int)(1 << 5);
	/// <i>native declaration : nsgui.h</i>
	public static final int AllValues = (int)15;
	/// <i>native declaration : nsgui.h</i>
	public static final int USPosition = (int)(1 << 0);
	/// <i>native declaration : nsgui.h</i>
	public static final int PBaseSize = (int)(1 << 8);
	/// <i>native declaration : nsgui.h</i>
	public static final int WidthValue = (int)4;
	/// <i>native declaration : nsgui.h</i>
	public static final int USSize = (int)(1 << 1);
	/// <i>native declaration : nsgui.h</i>
	public static final int CenterGravity = (int)5;
	/// <i>native declaration : nsgui.h</i>
	public static final int PAspect = (int)(1 << 7);
	/// <i>native declaration : nsgui.h</i>
	public static final int NorthEastGravity = (int)3;
	/// <i>native declaration : nsgui.h</i>
	public static final int WestGravity = (int)4;
	/// <i>native declaration : nsgui.h</i>
	public static final int XValue = (int)1;
	/// <i>native declaration : nsgui.h</i>
	public static final int NorthGravity = (int)2;
	/// <i>native declaration : nsgui.h</i>
	public static final int PResizeInc = (int)(1 << 6);
	/// <i>native declaration : nsgui.h</i>
	public static final int StaticGravity = (int)10;
	/// <i>native declaration : nsgui.h</i>
	public static final int ForgetGravity = (int)0;
	/// <i>native declaration : nsgui.h</i>
	public static final int No_Cursor = (int)(0);
	/// <i>native declaration : nsgui.h</i>
	public static final int SouthEastGravity = (int)9;
	/// <i>native declaration : nsgui.h</i>
	public static final int GCFont = (int)3;
	/// <i>native declaration : nsgui.h</i>
	public static final int PSize = (int)(1 << 3);
	/// <i>native declaration : nsgui.h</i>
	public static final int PPosition = (int)(1 << 2);
	/// <i>native declaration : nsgui.h</i>
	public static final int SouthGravity = (int)8;
	/// <i>native declaration : nsgui.h</i>
	public static final int PMinSize = (int)(1 << 4);
	/// <i>native declaration : nsgui.h</i>
	public static final int SouthWestGravity = (int)7;
	/// <i>native declaration : nsgui.h</i>
	public static final int YValue = (int)2;
	/// <i>native declaration : nsgui.h</i>
	public static final int GCForeground = (int)1;
	/// <i>native declaration : nsgui.h</i>
	public static final int NorthWestGravity = (int)1;
	/// <i>native declaration : nsgui.h</i>
	public static final int YNegative = (int)32;
	/// <i>native declaration : nsgui.h</i>
	public static final int XNegative = (int)16;
	/// <i>native declaration : nsgui.h</i>
	public static final int PWinGravity = (int)(1 << 9);
	/// <i>native declaration : nsgui.h</i>
	public static final int EastGravity = (int)6;
	/// <i>native declaration : nsgui.h</i>
	public static final int HeightValue = (int)8;
	/// <i>native declaration : nsgui.h</i>
	public static final int NoValue = (int)0;
}
