package emacs.nsgui;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : nsgui.h:49</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("nsgui") 
public class NSRect extends StructObject {
	public NSRect() {
		super();
	}
	/// C type : NSPoint
	@Field(0) 
	public NSPoint origin() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : NSPoint
	@Field(0) 
	public NSRect origin(NSPoint origin) {
		this.io.setNativeObjectField(this, 0, origin);
		return this;
	}
	/// C type : NSSize
	@Field(1) 
	public NSSize size() {
		return this.io.getNativeObjectField(this, 1);
	}
	/// C type : NSSize
	@Field(1) 
	public NSRect size(NSSize size) {
		this.io.setNativeObjectField(this, 1, size);
		return this;
	}
}
