package emacs.puresize;
import org.bridj.BridJ;
import org.bridj.CRuntime;
import org.bridj.ann.Library;
import org.bridj.ann.Runtime;
/**
 * Wrapper for library <b>puresize</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("puresize") 
@Runtime(CRuntime.class) 
public class PuresizeLibrary {
	static {
		BridJ.register();
	}
	/// <i>native declaration : puresize.h</i>
	public static final int PURESIZE_RATIO = (int)1;
	/// <i>native declaration : puresize.h</i>
	public static final int BASE_PURESIZE = (int)(1620000 + 0 + 0);
	/// <i>native declaration : puresize.h</i>
	public static final int PURESIZE = (int)((1620000 + 0 + 0) * 1 * 1);
	/// <i>native declaration : puresize.h</i>
	public static final int SYSTEM_PURESIZE_EXTRA = (int)0;
	/// <i>native declaration : puresize.h</i>
	public static final int SITELOAD_PURESIZE_EXTRA = (int)0;
	/// <i>native declaration : puresize.h</i>
	public static final int PURESIZE_CHECKING_RATIO = (int)1;
}
