package emacs.lisp;
import org.bridj.BridJ;
import org.bridj.CRuntime;
import org.bridj.ann.Library;
import org.bridj.ann.Runtime;
/**
 * Wrapper for library <b>lisp</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("lisp") 
@Runtime(CRuntime.class) 
public class LispLibrary {
	static {
		BridJ.register();
	}
	/// <i>native declaration : lisp.h</i>
	public static final int GC_USE_GCPROS_CHECK_ZOMBIES = (int)3;
	/// <i>native declaration : lisp.h</i>
	public static final int GCTYPEBITS = (int)3;
	/// <i>native declaration : lisp.h</i>
	public static final int CHAR_ALT = (int)(4194304);
	/// <i>native declaration : lisp.h</i>
	public static final int GLYPH_MODE_LINE_FACE = (int)1;
	/// <i>native declaration : lisp.h</i>
	public static final int GC_MARK_STACK = (int)0;
	/// <i>native declaration : lisp.h</i>
	public static final int MAX_ALLOCA = (int)16 * 1024;
	/// <i>native declaration : lisp.h</i>
	public static final int DEFAULT_HASH_SIZE = (int)65;
	/// <i>native declaration : lisp.h</i>
	public static final int COMPILED_ARGLIST = (int)0;
	/**
	 * define<br>
	 * Conversion Error : null<br>
	 * SKIPPED:<br>
	 * <i>native declaration : lisp.h</i><br>
	 * = 0
	 */
	/**
	 * define<br>
	 * Conversion Error : !(0 == 1 || 0 == 2)<br>
	 * SKIPPED:<br>
	 * <i>native declaration : lisp.h:0</i><br>
	 * !(0 == 1 || 0 == 2)
	 */
	/// <i>native declaration : lisp.h</i>
	public static final int CHAR_META = (int)(134217728);
	/// <i>native declaration : lisp.h</i>
	public static final double DEFAULT_REHASH_THRESHOLD = (double)0.8;
	/// <i>native declaration : lisp.h</i>
	public static final int LISP_STRING_TAG = (int)4;
	/// <i>native declaration : lisp.h</i>
	public static final int CHAR_CTL = (int)(67108864);
	/// <i>native declaration : lisp.h</i>
	public static final int CHARACTERBITS = (int)22;
	/// <i>native declaration : lisp.h</i>
	public static final int COMPILED_CONSTANTS = (int)2;
	/// <i>native declaration : lisp.h</i>
	public static final int FLOAT_TO_STRING_BUFSIZE = (int)350;
	/// <i>native declaration : lisp.h</i>
	public static final int COMPILED_BYTECODE = (int)1;
	/// <i>native declaration : lisp.h</i>
	public static final int COMPILED_STACK_DEPTH = (int)3;
	/// <i>native declaration : lisp.h</i>
	public static final int UNEVALLED = (int)-1;
	/// <i>native declaration : lisp.h</i>
	public static final int GC_USE_GCPROS_AS_BEFORE = (int)0;
	/// <i>native declaration : lisp.h</i>
	public static final int MANY = (int)-2;
	/// <i>native declaration : lisp.h</i>
	public static final int CHARTAB_SIZE_BITS_1 = (int)4;
	/// <i>native declaration : lisp.h</i>
	public static final int CHARTAB_SIZE_BITS_2 = (int)5;
	/// <i>native declaration : lisp.h</i>
	public static final int CHARTAB_SIZE_BITS_0 = (int)6;
	/// <i>native declaration : lisp.h</i>
	public static final int CHARTAB_SIZE_BITS_3 = (int)7;
	/// <i>native declaration : lisp.h</i>
	public static final int CHAR_SUPER = (int)(8388608);
	/// <i>native declaration : lisp.h</i>
	public static final String pD = (String)"t";
	/// <i>native declaration : lisp.h</i>
	public static final String pI = (String)"";
	/// <i>native declaration : lisp.h</i>
	public static final int GC_MARK_STACK_CHECK_GCPROS = (int)2;
	/// <i>native declaration : lisp.h</i>
	public static final int COMPILED_INTERACTIVE = (int)5;
	/// <i>native declaration : lisp.h</i>
	public static final int COMPILED_DOC_STRING = (int)4;
	/// <i>native declaration : lisp.h</i>
	public static final int BOOL_VECTOR_BITS_PER_CHAR = (int)8;
	/// <i>native declaration : lisp.h</i>
	public static final int PSEUDOVECTOR_SIZE_MASK = (int)511;
	/// <i>native declaration : lisp.h</i>
	public static final int GC_MAKE_GCPROS_NOOPS = (int)1;
	/// <i>native declaration : lisp.h</i>
	public static final double DEFAULT_REHASH_SIZE = (double)1.5;
	/// <i>native declaration : lisp.h</i>
	public static final char DIRECTORY_SEP = (char)'/';
	/// <i>native declaration : lisp.h</i>
	public static final int CHAR_SHIFT = (int)(33554432);
	/// <i>native declaration : lisp.h</i>
	public static final int CHAR_HYPER = (int)(16777216);
	/// <i>native declaration : lisp.h</i>
	public static final int LISP_INT1_TAG = (int)1;
	/// <i>native declaration : lisp.h</i>
	public static final int CHAR_MODIFIER_MASK = (int)((4194304) | (8388608) | (16777216) | (33554432) | (67108864) | (134217728));
	/// <i>native declaration : lisp.h</i>
	public static final String pMd = (String)"";
	/// <i>native declaration : lisp.h</i>
	public static final String pMu = (String)"";
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : lisp.h</i><br>
	 * ((void)0)
	 */
}
