package emacs.systty;
import org.bridj.StructObject;
import org.bridj.ann.Library;
/**
 * <i>native declaration : systty.h:1403</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("systty") 
public class emacs_tty extends StructObject {
	public emacs_tty() {
		super();
	}
}
