package emacs.emacs_icon;
import org.bridj.BridJ;
import org.bridj.CRuntime;
import org.bridj.ann.Library;
import org.bridj.ann.Runtime;
/**
 * Wrapper for library <b>emacs_icon</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("emacs_icon") 
@Runtime(CRuntime.class) 
public class Emacs_iconLibrary {
	static {
		BridJ.register();
	}
	/// <i>native declaration : emacs_icon.h</i>
	public static final int gnu_xbm_width = (int)50;
	/// <i>native declaration : emacs_icon.h</i>
	public static final int gnu_xbm_height = (int)50;
}
