package emacs.regex;
import emacs.regex.RegexLibrary.ssize_t;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This is the structure we store register match data in.  See<br>
 * regex.texinfo for a full description of what registers match.<br>
 * <i>native declaration : regex.h:126</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("regex") 
public class re_registers extends StructObject {
	public re_registers() {
		super();
	}
	@Field(0) 
	public int num_regs() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public re_registers num_regs(int num_regs) {
		this.io.setIntField(this, 0, num_regs);
		return this;
	}
	/// C type : regoff_t*
	@Field(1) 
	public Pointer<ssize_t > start() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : regoff_t*
	@Field(1) 
	public re_registers start(Pointer<ssize_t > start) {
		this.io.setPointerField(this, 1, start);
		return this;
	}
	/// C type : regoff_t*
	@Field(2) 
	public Pointer<ssize_t > end() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : regoff_t*
	@Field(2) 
	public re_registers end(Pointer<ssize_t > end) {
		this.io.setPointerField(this, 2, end);
		return this;
	}
}
