package emacs.menu;
import org.bridj.BridJ;
import org.bridj.CRuntime;
import org.bridj.Pointer;
import org.bridj.ann.Library;
import org.bridj.ann.Runtime;
/**
 * Wrapper for library <b>menu</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("menu") 
@Runtime(CRuntime.class) 
public class MenuLibrary {
	static {
		BridJ.register();
	}
	/**
	 * Original signature : <code>int set_file_times(const char*, int, int)</code><br>
	 * <i>native declaration : systime.h:303</i>
	 */
	public static native int set_file_times(Pointer<Byte > charPtr1, int int1, int int2);
	/**
	 * defined in keyboard.c<br>
	 * Original signature : <code>void set_waiting_for_input(int*)</code><br>
	 * <i>native declaration : systime.h:308</i>
	 */
	public static native void set_waiting_for_input(Pointer<Integer > intPtr1);
	/**
	 * Original signature : <code>void x_set_menu_bar_lines(frame*, Lisp_Object, Lisp_Object)</code><br>
	 * <i>native declaration : menu.h:310</i>
	 */
	public static native void x_set_menu_bar_lines(Pointer<MenuLibrary.frame > f, MenuLibrary.Lisp_Object value, MenuLibrary.Lisp_Object oldval);
	/**
	 * Original signature : <code>void init_menu_items()</code><br>
	 * <i>native declaration : menu.h:312</i>
	 */
	public static native void init_menu_items();
	/**
	 * Original signature : <code>void finish_menu_items()</code><br>
	 * <i>native declaration : menu.h:314</i>
	 */
	public static native void finish_menu_items();
	/**
	 * Original signature : <code>void discard_menu_items()</code><br>
	 * <i>native declaration : menu.h:316</i>
	 */
	public static native void discard_menu_items();
	/**
	 * Original signature : <code>void save_menu_items()</code><br>
	 * <i>native declaration : menu.h:318</i>
	 */
	public static native void save_menu_items();
	/**
	 * Original signature : <code>int parse_single_submenu()</code><br>
	 * <i>native declaration : menu.h:320</i>
	 */
	public static native int parse_single_submenu();
	/**
	 * Original signature : <code>void list_of_panes()</code><br>
	 * <i>native declaration : menu.h:322</i>
	 */
	public static native void list_of_panes();
	/**
	 * Original signature : <code>Lisp_Object w32_menu_show(int, int, int, int, Lisp_Object, const char**)</code><br>
	 * <i>native declaration : menu.h:324</i>
	 */
	public static native MenuLibrary.Lisp_Object w32_menu_show(int int1, int int2, int int3, int int4, MenuLibrary.Lisp_Object Lisp_Object1, Pointer<Pointer<Byte > > charPtrPtr1);
	/**
	 * Original signature : <code>Lisp_Object ns_menu_show(int, int, int, int, Lisp_Object, const char**)</code><br>
	 * <i>native declaration : menu.h:326</i>
	 */
	public static native MenuLibrary.Lisp_Object ns_menu_show(int int1, int int2, int int3, int int4, MenuLibrary.Lisp_Object Lisp_Object1, Pointer<Pointer<Byte > > charPtrPtr1);
	/**
	 * Original signature : <code>Lisp_Object xmenu_show(int, int, int, int, Lisp_Object, const char**)</code><br>
	 * <i>native declaration : menu.h:328</i>
	 */
	public static native MenuLibrary.Lisp_Object xmenu_show(int int1, int int2, int int3, int int4, MenuLibrary.Lisp_Object Lisp_Object1, Pointer<Pointer<Byte > > charPtrPtr1);
	/// Undefined type
	/// Undefined type
	public static interface frame {
		
	};
	/// Undefined type
	/// Undefined type
	public static interface Lisp_Object {
		
	};
}
