package emacs.xterm;
import emacs.xterm.XtermLibrary._XDisplay;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * For an event of kind SELECTION_REQUEST_EVENT,<br>
 * this structure really describes the contents.<br>
 * *Don't make this struct longer!**<br>
 * If it overlaps the frame_or_window field of struct input_event,<br>
 * that will cause GC to crash.<br>
 * <i>native declaration : xterm.h:3043</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("xterm") 
public class selection_input_event extends StructObject {
	public selection_input_event() {
		super();
	}
	@Field(0) 
	public int kind() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public selection_input_event kind(int kind) {
		this.io.setIntField(this, 0, kind);
		return this;
	}
	/// C type : Display*
	@Field(1) 
	public Pointer<_XDisplay > display() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : Display*
	@Field(1) 
	public selection_input_event display(Pointer<_XDisplay > display) {
		this.io.setPointerField(this, 1, display);
		return this;
	}
	/**
	 * We spell it with an "o" here because X does.<br>
	 * C type : Window
	 */
	@CLong 
	@Field(2) 
	public long requestor() {
		return this.io.getCLongField(this, 2);
	}
	/**
	 * We spell it with an "o" here because X does.<br>
	 * C type : Window
	 */
	@CLong 
	@Field(2) 
	public selection_input_event requestor(long requestor) {
		this.io.setCLongField(this, 2, requestor);
		return this;
	}
	/// C type : Atom
	@CLong 
	@Field(3) 
	public long selection() {
		return this.io.getCLongField(this, 3);
	}
	/// C type : Atom
	@CLong 
	@Field(3) 
	public selection_input_event selection(long selection) {
		this.io.setCLongField(this, 3, selection);
		return this;
	}
	/// C type : Atom
	@CLong 
	@Field(4) 
	public long target() {
		return this.io.getCLongField(this, 4);
	}
	/// C type : Atom
	@CLong 
	@Field(4) 
	public selection_input_event target(long target) {
		this.io.setCLongField(this, 4, target);
		return this;
	}
	/// C type : Atom
	@CLong 
	@Field(5) 
	public long property() {
		return this.io.getCLongField(this, 5);
	}
	/// C type : Atom
	@CLong 
	@Field(5) 
	public selection_input_event property(long property) {
		this.io.setCLongField(this, 5, property);
		return this;
	}
	/// C type : Time
	@CLong 
	@Field(6) 
	public long time() {
		return this.io.getCLongField(this, 6);
	}
	/// C type : Time
	@CLong 
	@Field(6) 
	public selection_input_event time(long time) {
		this.io.setCLongField(this, 6, time);
		return this;
	}
}
