package emacs.widgetprv;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : widgetprv.h:4227</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("widgetprv") 
public class ArgList_struct extends StructObject {
	public ArgList_struct() {
		super();
	}
	/// C type : String
	@Field(0) 
	public Pointer<Byte > name() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : String
	@Field(0) 
	public ArgList_struct name(Pointer<Byte > name) {
		this.io.setPointerField(this, 0, name);
		return this;
	}
	/// C type : XtArgVal
	@CLong 
	@Field(1) 
	public long value() {
		return this.io.getCLongField(this, 1);
	}
	/// C type : XtArgVal
	@CLong 
	@Field(1) 
	public ArgList_struct value(long value) {
		this.io.setCLongField(this, 1, value);
		return this;
	}
}
