package emacs.widgetprv;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : widgetprv.h:4263</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("widgetprv") 
public class XtTypedArgList_struct extends StructObject {
	public XtTypedArgList_struct() {
		super();
	}
	/**
	 * resource name<br>
	 * C type : String
	 */
	@Field(0) 
	public Pointer<Byte > name() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * resource name<br>
	 * C type : String
	 */
	@Field(0) 
	public XtTypedArgList_struct name(Pointer<Byte > name) {
		this.io.setPointerField(this, 0, name);
		return this;
	}
	/**
	 * representation type name<br>
	 * C type : String
	 */
	@Field(1) 
	public Pointer<Byte > type() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * representation type name<br>
	 * C type : String
	 */
	@Field(1) 
	public XtTypedArgList_struct type(Pointer<Byte > type) {
		this.io.setPointerField(this, 1, type);
		return this;
	}
	/**
	 * representation<br>
	 * C type : XtArgVal
	 */
	@CLong 
	@Field(2) 
	public long value() {
		return this.io.getCLongField(this, 2);
	}
	/**
	 * representation<br>
	 * C type : XtArgVal
	 */
	@CLong 
	@Field(2) 
	public XtTypedArgList_struct value(long value) {
		this.io.setCLongField(this, 2, value);
		return this;
	}
	/// size of representation
	@Field(3) 
	public int size() {
		return this.io.getIntField(this, 3);
	}
	/// size of representation
	@Field(3) 
	public XtTypedArgList_struct size(int size) {
		this.io.setIntField(this, 3, size);
		return this;
	}
}
