package emacs.nsterm;
import emacs.nsterm.NstermLibrary.bidi_dir_t;
import emacs.nsterm.NstermLibrary.bidi_type_t;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Bits;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * Data type for reordering bidirectional text.<br>
 * <i>native declaration : dispextern.h:922</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("nsterm") 
public class bidi_it extends StructObject {
	public bidi_it() {
		super();
	}
	/**
	 * character at that position, or u+FFFC<br>
	 * ("object replacement character") for a run<br>
	 * of characters covered by a display string
	 */
	@Field(2) 
	public int ch() {
		return this.io.getIntField(this, 2);
	}
	/**
	 * character at that position, or u+FFFC<br>
	 * ("object replacement character") for a run<br>
	 * of characters covered by a display string
	 */
	@Field(2) 
	public bidi_it ch(int ch) {
		this.io.setIntField(this, 2, ch);
		return this;
	}
	/**
	 * bidi type of this character, after<br>
	 * resolving weak and neutral types<br>
	 * C type : bidi_type_t
	 */
	@Field(5) 
	public IntValuedEnum<bidi_type_t > type() {
		return this.io.getEnumField(this, 5);
	}
	/**
	 * bidi type of this character, after<br>
	 * resolving weak and neutral types<br>
	 * C type : bidi_type_t
	 */
	@Field(5) 
	public bidi_it type(IntValuedEnum<bidi_type_t > type) {
		this.io.setEnumField(this, 5, type);
		return this;
	}
	/**
	 * original type, after overrides and W1<br>
	 * C type : bidi_type_t
	 */
	@Field(6) 
	public IntValuedEnum<bidi_type_t > type_after_w1() {
		return this.io.getEnumField(this, 6);
	}
	/**
	 * original type, after overrides and W1<br>
	 * C type : bidi_type_t
	 */
	@Field(6) 
	public bidi_it type_after_w1(IntValuedEnum<bidi_type_t > type_after_w1) {
		this.io.setEnumField(this, 6, type_after_w1);
		return this;
	}
	/**
	 * original type, as found in the buffer<br>
	 * C type : bidi_type_t
	 */
	@Field(7) 
	public IntValuedEnum<bidi_type_t > orig_type() {
		return this.io.getEnumField(this, 7);
	}
	/**
	 * original type, as found in the buffer<br>
	 * C type : bidi_type_t
	 */
	@Field(7) 
	public bidi_it orig_type(IntValuedEnum<bidi_type_t > orig_type) {
		this.io.setEnumField(this, 7, orig_type);
		return this;
	}
	/// final resolved level of this character
	@Field(8) 
	public int resolved_level() {
		return this.io.getIntField(this, 8);
	}
	/// final resolved level of this character
	@Field(8) 
	public bidi_it resolved_level(int resolved_level) {
		this.io.setIntField(this, 8, resolved_level);
		return this;
	}
	/// how many PDFs to ignore
	@Field(9) 
	public int invalid_levels() {
		return this.io.getIntField(this, 9);
	}
	/// how many PDFs to ignore
	@Field(9) 
	public bidi_it invalid_levels(int invalid_levels) {
		this.io.setIntField(this, 9, invalid_levels);
		return this;
	}
	/// how many PDFs from RLE/RLO to ignore
	@Field(10) 
	public int invalid_rl_levels() {
		return this.io.getIntField(this, 10);
	}
	/// how many PDFs from RLE/RLO to ignore
	@Field(10) 
	public bidi_it invalid_rl_levels(int invalid_rl_levels) {
		this.io.setIntField(this, 10, invalid_rl_levels);
		return this;
	}
	/// if non-zero, previous char was PDF
	@Field(11) 
	public int prev_was_pdf() {
		return this.io.getIntField(this, 11);
	}
	/// if non-zero, previous char was PDF
	@Field(11) 
	public bidi_it prev_was_pdf(int prev_was_pdf) {
		this.io.setIntField(this, 11, prev_was_pdf);
		return this;
	}
	/**
	 * info about previous character<br>
	 * C type : bidi_saved_info
	 */
	@Field(12) 
	public bidi_saved_info prev() {
		return this.io.getNativeObjectField(this, 12);
	}
	/**
	 * info about previous character<br>
	 * C type : bidi_saved_info
	 */
	@Field(12) 
	public bidi_it prev(bidi_saved_info prev) {
		this.io.setNativeObjectField(this, 12, prev);
		return this;
	}
	/**
	 * last-seen strong directional char<br>
	 * C type : bidi_saved_info
	 */
	@Field(13) 
	public bidi_saved_info last_strong() {
		return this.io.getNativeObjectField(this, 13);
	}
	/**
	 * last-seen strong directional char<br>
	 * C type : bidi_saved_info
	 */
	@Field(13) 
	public bidi_it last_strong(bidi_saved_info last_strong) {
		this.io.setNativeObjectField(this, 13, last_strong);
		return this;
	}
	/**
	 * surrounding characters for...<br>
	 * C type : bidi_saved_info
	 */
	@Field(14) 
	public bidi_saved_info next_for_neutral() {
		return this.io.getNativeObjectField(this, 14);
	}
	/**
	 * surrounding characters for...<br>
	 * C type : bidi_saved_info
	 */
	@Field(14) 
	public bidi_it next_for_neutral(bidi_saved_info next_for_neutral) {
		this.io.setNativeObjectField(this, 14, next_for_neutral);
		return this;
	}
	/**
	 * ...resolving neutrals<br>
	 * C type : bidi_saved_info
	 */
	@Field(15) 
	public bidi_saved_info prev_for_neutral() {
		return this.io.getNativeObjectField(this, 15);
	}
	/**
	 * ...resolving neutrals<br>
	 * C type : bidi_saved_info
	 */
	@Field(15) 
	public bidi_it prev_for_neutral(bidi_saved_info prev_for_neutral) {
		this.io.setNativeObjectField(this, 15, prev_for_neutral);
		return this;
	}
	/**
	 * character after sequence of ws<br>
	 * C type : bidi_saved_info
	 */
	@Field(16) 
	public bidi_saved_info next_for_ws() {
		return this.io.getNativeObjectField(this, 16);
	}
	/**
	 * character after sequence of ws<br>
	 * C type : bidi_saved_info
	 */
	@Field(16) 
	public bidi_it next_for_ws(bidi_saved_info next_for_ws) {
		this.io.setNativeObjectField(this, 16, next_for_ws);
		return this;
	}
	/**
	 * type of char at next_en_pos<br>
	 * C type : bidi_type_t
	 */
	@Field(18) 
	public IntValuedEnum<bidi_type_t > next_en_type() {
		return this.io.getEnumField(this, 18);
	}
	/**
	 * type of char at next_en_pos<br>
	 * C type : bidi_type_t
	 */
	@Field(18) 
	public bidi_it next_en_type(IntValuedEnum<bidi_type_t > next_en_type) {
		this.io.setEnumField(this, 18, next_en_type);
		return this;
	}
	/**
	 * direction of start-of-run in effect<br>
	 * C type : bidi_dir_t
	 */
	@Field(20) 
	public IntValuedEnum<bidi_dir_t > sor() {
		return this.io.getEnumField(this, 20);
	}
	/**
	 * direction of start-of-run in effect<br>
	 * C type : bidi_dir_t
	 */
	@Field(20) 
	public bidi_it sor(IntValuedEnum<bidi_dir_t > sor) {
		this.io.setEnumField(this, 20, sor);
		return this;
	}
	/// direction of text scan, 1: forw, -1: back
	@Field(21) 
	public int scan_dir() {
		return this.io.getIntField(this, 21);
	}
	/// direction of text scan, 1: forw, -1: back
	@Field(21) 
	public bidi_it scan_dir(int scan_dir) {
		this.io.setIntField(this, 21, scan_dir);
		return this;
	}
	/**
	 * if non-zero, there really is a<br>
	 * `display' property/string at disp_pos;<br>
	 * if 2, the property is a `space' spec
	 */
	@Field(23) 
	public int disp_prop() {
		return this.io.getIntField(this, 23);
	}
	/**
	 * if non-zero, there really is a<br>
	 * `display' property/string at disp_pos;<br>
	 * if 2, the property is a `space' spec
	 */
	@Field(23) 
	public bidi_it disp_prop(int disp_prop) {
		this.io.setIntField(this, 23, disp_prop);
		return this;
	}
	/// index of current data on the stack
	@Field(24) 
	public int stack_idx() {
		return this.io.getIntField(this, 24);
	}
	/// index of current data on the stack
	@Field(24) 
	public bidi_it stack_idx(int stack_idx) {
		this.io.setIntField(this, 24, stack_idx);
		return this;
	}
	/**
	 * Note: Everything from here on is not copied/saved when the bidi<br>
	 * iterator state is saved, pushed, or popped.  So only put here<br>
	 * stuff that is not part of the bidi iterator's state!<br>
	 * stack of embedding levels<br>
	 * C type : bidi_stack[64]
	 */
	@Array({64}) 
	@Field(25) 
	public Pointer<bidi_stack > level_stack() {
		return this.io.getPointerField(this, 25);
	}
	/**
	 * string to reorder<br>
	 * C type : bidi_string_data
	 */
	@Field(26) 
	public bidi_string_data string() {
		return this.io.getNativeObjectField(this, 26);
	}
	/**
	 * string to reorder<br>
	 * C type : bidi_string_data
	 */
	@Field(26) 
	public bidi_it string(bidi_string_data string) {
		this.io.setNativeObjectField(this, 26, string);
		return this;
	}
	/**
	 * current paragraph direction<br>
	 * C type : bidi_dir_t
	 */
	@Field(27) 
	public IntValuedEnum<bidi_dir_t > paragraph_dir() {
		return this.io.getEnumField(this, 27);
	}
	/**
	 * current paragraph direction<br>
	 * C type : bidi_dir_t
	 */
	@Field(27) 
	public bidi_it paragraph_dir(IntValuedEnum<bidi_dir_t > paragraph_dir) {
		this.io.setEnumField(this, 27, paragraph_dir);
		return this;
	}
	/// if non-zero, examine current char first
	@Field(29) 
	@Bits(1) 
	public int first_elt() {
		return this.io.getIntField(this, 29);
	}
	/// if non-zero, examine current char first
	@Field(29) 
	@Bits(1) 
	public bidi_it first_elt(int first_elt) {
		this.io.setIntField(this, 29, first_elt);
		return this;
	}
	/// if non-zero, we expect a new paragraph
	@Field(30) 
	@Bits(1) 
	public int new_paragraph() {
		return this.io.getIntField(this, 30);
	}
	/// if non-zero, we expect a new paragraph
	@Field(30) 
	@Bits(1) 
	public bidi_it new_paragraph(int new_paragraph) {
		this.io.setIntField(this, 30, new_paragraph);
		return this;
	}
	/// non-zero if displaying on a GUI frame
	@Field(31) 
	@Bits(1) 
	public int frame_window_p() {
		return this.io.getIntField(this, 31);
	}
	/// non-zero if displaying on a GUI frame
	@Field(31) 
	@Bits(1) 
	public bidi_it frame_window_p(int frame_window_p) {
		this.io.setIntField(this, 31, frame_window_p);
		return this;
	}
}
