package emacs.nsterm;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : font.h:3002</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("nsterm") 
public class font_metrics extends StructObject {
	public font_metrics() {
		super();
	}
	@Field(0) 
	public short lbearing() {
		return this.io.getShortField(this, 0);
	}
	@Field(0) 
	public font_metrics lbearing(short lbearing) {
		this.io.setShortField(this, 0, lbearing);
		return this;
	}
	@Field(1) 
	public short rbearing() {
		return this.io.getShortField(this, 1);
	}
	@Field(1) 
	public font_metrics rbearing(short rbearing) {
		this.io.setShortField(this, 1, rbearing);
		return this;
	}
	@Field(2) 
	public short width() {
		return this.io.getShortField(this, 2);
	}
	@Field(2) 
	public font_metrics width(short width) {
		this.io.setShortField(this, 2, width);
		return this;
	}
	@Field(3) 
	public short ascent() {
		return this.io.getShortField(this, 3);
	}
	@Field(3) 
	public font_metrics ascent(short ascent) {
		this.io.setShortField(this, 3, ascent);
		return this;
	}
	@Field(4) 
	public short descent() {
		return this.io.getShortField(this, 4);
	}
	@Field(4) 
	public font_metrics descent(short descent) {
		this.io.setShortField(this, 4, descent);
		return this;
	}
}
